#!/usr/bin/env node
/**
 * gen-status.mjs — renders docs/STATUS.md from the program manifest and validates that every
 * extracted source file carries an @extracted-from origin header.
 *
 * The manifest lives at the program level (../docs/manifest/components.json) while the repos
 * share a root; when driverse-ui is split into its own repo, vendor the manifest in.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const LIB = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MANIFEST = path.join(LIB, "..", "docs", "manifest", "components.json");
const SRC = path.join(LIB, "src");

const manifest = JSON.parse(fs.readFileSync(MANIFEST, "utf8"));

function walk(dir) {
	if (!fs.existsSync(dir)) return [];
	const out = [];
	for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
		const p = path.join(dir, e.name);
		if (e.isDirectory()) out.push(...walk(p));
		else out.push(p);
	}
	return out;
}

// Header validation: every non-test/story/index ts(x) source must carry @extracted-from
// unless it is marked lib-native with @lib-native.
const missing = [];
for (const f of walk(SRC)) {
	if (!/\.(ts|tsx)$/.test(f)) continue;
	if (/\.(test|stories)\.tsx?$/.test(f)) continue;
	if (path.basename(f) === "index.ts") continue;
	const head = fs.readFileSync(f, "utf8").slice(0, 600);
	if (!head.includes("@extracted-from") && !head.includes("@lib-native")) missing.push(path.relative(LIB, f));
}

// Extraction progress: a unit counts as started when its target dir/file exists in src/.
const rows = manifest.units
	.filter((u) => u.tier !== "X")
	.map((u) => {
		const target = u.target?.replace(/^src\//, "");
		const exists = target
			? fs.existsSync(path.join(SRC, target)) || fs.existsSync(path.join(SRC, `${target}.ts`))
			: false;
		return { ...u, extracted: exists };
	});
const done = rows.filter((r) => r.extracted);

let md = `# Extraction Status

> Generated by \`scripts/gen-status.mjs\` from the program manifest — do not edit by hand.
> Program docs: [../../docs/PLAN.md](../../docs/PLAN.md) · [../../docs/INDEX.md](../../docs/INDEX.md)

**${done.length} / ${rows.length}** planned units extracted.

| Unit | Tier | Wave | Decision | Target | Extracted |
|---|---|---|---|---|---|
`;
for (const r of rows.sort((a, b) => `${a.wave}${a.id}`.localeCompare(`${b.wave}${b.id}`))) {
	md += `| ${r.id} | ${r.tier === "F" ? "F" : `T${r.tier}`} | ${r.wave} | ${r.decision} | ${r.target ? `\`${r.target}\`` : "—"} | ${r.extracted ? "✅" : "▫️"} |\n`;
}
if (missing.length) {
	md += `\n## ⚠️ Files missing an origin header\n\n${missing.map((m) => `- \`${m}\``).join("\n")}\n`;
}
fs.mkdirSync(path.join(LIB, "docs"), { recursive: true });
fs.writeFileSync(path.join(LIB, "docs", "STATUS.md"), md);

console.log(`STATUS.md: ${done.length}/${rows.length} units extracted; ${missing.length} file(s) missing headers`);
if (missing.length) {
	console.error("Missing @extracted-from/@lib-native headers:");
	for (const m of missing) console.error(`  ${m}`);
	process.exit(1);
}
